<Release Title>

# 🔨 Build from source
git clone https://github.com/TessorNetwork/tessor
cd tessor && git checkout  v0.5.0-Tessor.1
make build
```

# ⚡️ Download binaries
Binaries for linux amd64 and arm64 are available below.
