version: "3"
services:
  tessor1:
    image: tessorzone:tessor
    volumes:
      - ./state/tessor1:/home/tessor/.tessor
    ports:
      - "26657:26657"
      - "1317:1317"
      - "9090:9090"

  tessor2:
    image: tessorzone:tessor
    volumes:
      - ./state/tessor2:/home/tessor/.tessor

  tessor3:
    image: tessorzone:tessor
    volumes:
      - ./state/tessor3:/home/tessor/.tessor

  gaia1:
    image: tessorzone:gaia
    volumes:
      - ./state/gaia1:/home/gaia/.gaia
    ports:
      - "26557:26657"
      - "1307:1317"
      - "9080:9090"

  gaia2:
    image: tessorzone:gaia
    volumes:
      - ./state/gaia2:/home/gaia/.gaia

  gaia3:
    image: tessorzone:gaia
    volumes:
      - ./state/gaia3:/home/gaia/.gaia

  gaia4:
    image: tessorzone:gaia
    volumes:
      - ./state/gaia4:/home/gaia/.gaia

  gaia5:
    image: tessorzone:gaia
    volumes:
      - ./state/gaia5:/home/gaia/.gaia

  juno1:
    image: tessorzone:juno
    volumes:
      - ./state/juno1:/home/juno/.juno
    ports:
      - "26457:26657"
      - "1297:1317"
      - "9070:9090"

  juno2:
    image: tessorzone:juno
    volumes:
      - ./state/juno2:/home/juno/.juno

  juno3:
    image: tessorzone:juno
    volumes:
      - ./state/juno3:/home/juno/.juno

  juno4:
    image: tessorzone:juno
    volumes:
      - ./state/juno4:/home/juno/.juno

  juno5:
    image: tessorzone:juno
    volumes:
      - ./state/juno5:/home/juno/.juno

  osmo1:
    image: tessorzone:osmo
    volumes:
      - ./state/osmo1:/home/osmosis/.osmosisd
    ports:
      - "26357:26657"
      - "1287:1317"
      - "9060:9090"

  osmo2:
    image: tessorzone:osmo
    volumes:
      - ./state/osmo2:/home/osmosis/.osmosisd

  osmo3:
    image: tessorzone:osmo
    volumes:
      - ./state/osmo3:/home/osmosis/.osmosisd

  osmo4:
    image: tessorzone:osmo
    volumes:
      - ./state/osmo4:/home/osmosis/.osmosisd

  osmo5:
    image: tessorzone:osmo
    volumes:
      - ./state/osmo5:/home/osmosis/.osmosisd

  stars1:
    image: tessorzone:stars
    volumes:
      - ./state/stars1:/home/stars/.starsd
    ports:
      - "26257:26657"
      - "1277:1317"
      - "9050:9090"

  stars2:
    image: tessorzone:stars
    volumes:
      - ./state/stars2:/home/stars/.starsd

  stars3:
    image: tessorzone:stars
    volumes:
      - ./state/stars3:/home/stars/.starsd

  stars4:
    image: tessorzone:stars
    volumes:
      - ./state/stars4:/home/stars/.starsd

  stars5:
    image: tessorzone:stars
    volumes:
      - ./state/stars5:/home/stars/.starsd

  host1:
    image: tessorzone:tessor
    volumes:
      - ./state/host1:/home/tessor/.tessor
    ports:
      - "26157:26657"
      - "1267:1317"
      - "9040:9090"

  host2:
    image: tessorzone:tessor
    volumes:
      - ./state/host2:/home/tessor/.tessor

  host3:
    image: tessorzone:tessor
    volumes:
      - ./state/host3:/home/tessor/.tessor

  host4:
    image: tessorzone:tessor
    volumes:
      - ./state/host4:/home/tessor/.tessor

  host5:
    image: tessorzone:tessor
    volumes:
      - ./state/host5:/home/tessor/.tessor

  # Fill in new host zone being tested here

  hermes:
    image: tessorzone:hermes
    volumes:
      - ~/.hermes:/home/hermes/.hermes
      - ./state/hermes/config.toml:/home/hermes/.hermes/config.toml
    restart: always

  relayer-gaia:
    image: tessorzone:relayer
    volumes:
      - ./state/relayer-gaia:/home/relayer/.relayer
    restart: always
    command: [ "bash", "start.sh", "tessor-gaia" ]

  relayer-juno:
    image: tessorzone:relayer
    volumes:
      - ./state/relayer-juno:/home/relayer/.relayer
    restart: always
    command: [ "bash", "start.sh", "tessor-juno" ]

  relayer-osmo:
    image: tessorzone:relayer
    volumes:
      - ./state/relayer-osmo:/home/relayer/.relayer
    restart: always
    command: [ "bash", "start.sh", "tessor-osmo" ]

  relayer-stars:
    image: tessorzone:relayer
    volumes:
      - ./state/relayer-stars:/home/relayer/.relayer
    restart: always
    command: [ "bash", "start.sh", "tessor-stars" ]

  relayer-host:
    image: tessorzone:relayer
    volumes:
      - ./state/relayer-host:/home/relayer/.relayer
    restart: always
    command: [ "bash", "start.sh", "tessor-host" ]
