version: "3"
services:
  tessor1:
    image: tessorzone:tessor
    volumes:
      - ../state/tessor1:/home/tessor/.tessor
    ports:
      - "26657:26657"
      - "1317:1317"
      - "9090:9090"

  hermes:
    image: tessorzone:hermes
    volumes:
      - ~/.hermes:/home/hermes/.hermes
      - ../state/hermes/config.toml:/home/hermes/.hermes/config.toml
    restart: always

  relayer:
    image: tessorzone:relayer
    volumes:
      - ../state/relayer:/home/relayer/.relayer
    restart: always
    command: [ "bash", "start.sh", "tessor-host" ]
